# Generated by Django 5.1.6 on 2026-03-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='created_at',
        ),
    ]
